apiVersion: v1
kind: Secret
metadata:
  name: octarine-{{ .Release.Name }}
  namespace:  {{ .Release.Namespace }}
  labels:
    chart: octarine
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: "kubernetes.io/octarine"
data:
  octactl.yaml: {{ include "octactl.yaml" .  | b64enc | quote }}
  octarine_docker_credentials: {{ include "octarine_docker_credentials" .  | b64enc | quote }}
  octarine-install.sh: {{ include "octarine-install" . |b64enc |quote }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    chart: octarine
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: docker-registry-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockercfg
data: {.dockercfg: {{ include "dockercfg" . | b64enc | quote }}}
